import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const colleges = [
  {
    name: 'IIT Bombay',
    slug: 'iit-bombay',
    location: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    type: 'Public',
    category: 'Engineering',
    rating: 4.8,
    reviewCount: 1240,
    annualFees: 230000,
    establishedYear: 1958,
    totalStudents: 10000,
    description: 'Indian Institute of Technology Bombay is one of the premier engineering institutions in India. Located in Powai, Mumbai, it offers world-class education in engineering, science, and technology. IIT Bombay consistently ranks among the top universities in Asia and is known for its cutting-edge research and vibrant campus life.',
    website: 'https://www.iitb.ac.in',
    avgPackage: 2000000,
    highestPackage: 10000000,
    placementRate: 96,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 230000, seats: 120 },
      { name: 'B.Tech Electrical Engineering', duration: 4, fees: 230000, seats: 90 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, fees: 230000, seats: 90 },
      { name: 'M.Tech Computer Science', duration: 2, fees: 200000, seats: 60 },
      { name: 'MBA', duration: 2, fees: 400000, seats: 60 },
    ],
  },
  {
    name: 'IIT Delhi',
    slug: 'iit-delhi',
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    type: 'Public',
    category: 'Engineering',
    rating: 4.7,
    reviewCount: 980,
    annualFees: 220000,
    establishedYear: 1961,
    totalStudents: 8500,
    description: 'IIT Delhi, established in 1961, is one of India\'s most prestigious engineering institutions. Situated in Hauz Khas, New Delhi, it is renowned for its research output, alumni network, and industry connections. The institute offers programs across engineering, science, and management disciplines.',
    website: 'https://home.iitd.ac.in',
    avgPackage: 1900000,
    highestPackage: 9500000,
    placementRate: 95,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 220000, seats: 100 },
      { name: 'B.Tech Electronics', duration: 4, fees: 220000, seats: 80 },
      { name: 'B.Tech Civil Engineering', duration: 4, fees: 220000, seats: 60 },
      { name: 'M.Tech Data Science', duration: 2, fees: 190000, seats: 40 },
    ],
  },
  {
    name: 'IIT Madras',
    slug: 'iit-madras',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    type: 'Public',
    category: 'Engineering',
    rating: 4.8,
    reviewCount: 1100,
    annualFees: 210000,
    establishedYear: 1959,
    totalStudents: 9000,
    description: 'IIT Madras, India\'s top-ranked institute, is nestled in a forested campus in Chennai. It leads in research, entrepreneurship, and innovation. The institute is home to numerous centers of excellence and start-ups, making it a hub for technology and innovation in South India.',
    website: 'https://www.iitm.ac.in',
    avgPackage: 2100000,
    highestPackage: 11000000,
    placementRate: 97,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 210000, seats: 110 },
      { name: 'B.Tech Aerospace Engineering', duration: 4, fees: 210000, seats: 40 },
      { name: 'B.Tech Chemical Engineering', duration: 4, fees: 210000, seats: 50 },
      { name: 'M.S. Research', duration: 2, fees: 180000, seats: 200 },
    ],
  },
  {
    name: 'BITS Pilani',
    slug: 'bits-pilani',
    location: 'Pilani, Rajasthan',
    city: 'Pilani',
    state: 'Rajasthan',
    type: 'Deemed',
    category: 'Engineering',
    rating: 4.5,
    reviewCount: 870,
    annualFees: 500000,
    establishedYear: 1964,
    totalStudents: 15000,
    description: 'BITS Pilani is one of India\'s most renowned private engineering universities. Known for its rigorous academics, practice school program, and strong industry connections, BITS produces some of the country\'s finest engineers and entrepreneurs. The Pilani campus spans 328 acres in Rajasthan.',
    website: 'https://www.bits-pilani.ac.in',
    avgPackage: 1600000,
    highestPackage: 8000000,
    placementRate: 91,
    courses: [
      { name: 'B.E. Computer Science', duration: 4, fees: 500000, seats: 200 },
      { name: 'B.E. Electronics & Communication', duration: 4, fees: 500000, seats: 180 },
      { name: 'M.Sc. Mathematics', duration: 5, fees: 480000, seats: 60 },
      { name: 'M.B.A.', duration: 2, fees: 600000, seats: 80 },
    ],
  },
  {
    name: 'NIT Trichy',
    slug: 'nit-trichy',
    location: 'Tiruchirappalli, Tamil Nadu',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    type: 'Public',
    category: 'Engineering',
    rating: 4.3,
    reviewCount: 650,
    annualFees: 150000,
    establishedYear: 1964,
    totalStudents: 6000,
    description: 'NIT Trichy, one of the 31 NITs in India, is consistently ranked among the top technical institutions. The institute is known for its excellent faculty, state-of-the-art infrastructure, and strong placement record. Located in Tiruchirappalli, it offers undergraduate and postgraduate programs in engineering and technology.',
    website: 'https://www.nitt.edu',
    avgPackage: 1100000,
    highestPackage: 4500000,
    placementRate: 88,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 150000, seats: 90 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, fees: 150000, seats: 90 },
      { name: 'B.Tech Civil Engineering', duration: 4, fees: 150000, seats: 60 },
      { name: 'M.Tech Computer Science', duration: 2, fees: 120000, seats: 30 },
    ],
  },
  {
    name: 'VIT Vellore',
    slug: 'vit-vellore',
    location: 'Vellore, Tamil Nadu',
    city: 'Vellore',
    state: 'Tamil Nadu',
    type: 'Deemed',
    category: 'Engineering',
    rating: 4.1,
    reviewCount: 2100,
    annualFees: 320000,
    establishedYear: 1984,
    totalStudents: 50000,
    description: 'VIT Vellore is one of India\'s largest private universities, known for its excellent infrastructure, international collaborations, and strong placement record. With over 50,000 students from across India and abroad, VIT offers a vibrant multicultural campus experience and industry-oriented curriculum.',
    website: 'https://vit.ac.in',
    avgPackage: 800000,
    highestPackage: 4400000,
    placementRate: 85,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 320000, seats: 1000 },
      { name: 'B.Tech AI & Machine Learning', duration: 4, fees: 350000, seats: 300 },
      { name: 'B.Tech Electronics', duration: 4, fees: 320000, seats: 500 },
      { name: 'M.Tech Software Engineering', duration: 2, fees: 250000, seats: 120 },
      { name: 'MBA', duration: 2, fees: 400000, seats: 200 },
    ],
  },
  {
    name: 'Manipal Institute of Technology',
    slug: 'manipal-institute-of-technology',
    location: 'Manipal, Karnataka',
    city: 'Manipal',
    state: 'Karnataka',
    type: 'Deemed',
    category: 'Engineering',
    rating: 4.0,
    reviewCount: 1450,
    annualFees: 380000,
    establishedYear: 1957,
    totalStudents: 15000,
    description: 'Manipal Institute of Technology (MIT), part of the prestigious Manipal Academy of Higher Education, is one of India\'s oldest private engineering colleges. Located in the picturesque coastal town of Manipal, Karnataka, the institute offers a wide range of engineering programs with strong industry connections.',
    website: 'https://manipal.edu/mit',
    avgPackage: 750000,
    highestPackage: 3500000,
    placementRate: 82,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 380000, seats: 400 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, fees: 360000, seats: 200 },
      { name: 'B.Tech Biomedical Engineering', duration: 4, fees: 360000, seats: 60 },
      { name: 'M.Tech Computer Science', duration: 2, fees: 280000, seats: 60 },
    ],
  },
  {
    name: 'SRM Institute of Science and Technology',
    slug: 'srm-institute',
    location: 'Kattankulathur, Tamil Nadu',
    city: 'Kattankulathur',
    state: 'Tamil Nadu',
    type: 'Deemed',
    category: 'Engineering',
    rating: 3.8,
    reviewCount: 1890,
    annualFees: 250000,
    establishedYear: 1985,
    totalStudents: 52000,
    description: 'SRM Institute of Science and Technology is one of India\'s top-ranked universities, with a vast campus in Kattankulathur near Chennai. Known for its diverse programs, international collaborations, and active placement cell, SRM attracts students from across India and over 60 countries worldwide.',
    website: 'https://www.srmist.edu.in',
    avgPackage: 650000,
    highestPackage: 3200000,
    placementRate: 80,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 250000, seats: 1200 },
      { name: 'B.Tech Data Science', duration: 4, fees: 280000, seats: 300 },
      { name: 'MBBS', duration: 5, fees: 1200000, seats: 150 },
      { name: 'MBA', duration: 2, fees: 350000, seats: 300 },
      { name: 'B.Sc Nursing', duration: 4, fees: 180000, seats: 100 },
    ],
  },
  {
    name: 'Amity University',
    slug: 'amity-university-noida',
    location: 'Noida, Uttar Pradesh',
    city: 'Noida',
    state: 'Uttar Pradesh',
    type: 'Private',
    category: 'Engineering',
    rating: 3.7,
    reviewCount: 2300,
    annualFees: 300000,
    establishedYear: 2005,
    totalStudents: 125000,
    description: 'Amity University, Noida is one of India\'s largest private universities with campuses across India and internationally. It offers a comprehensive range of programs across engineering, management, law, and arts. Known for its focus on holistic development, Amity provides exposure to industry and global academic standards.',
    website: 'https://www.amity.edu',
    avgPackage: 600000,
    highestPackage: 2800000,
    placementRate: 78,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 300000, seats: 800 },
      { name: 'BBA', duration: 3, fees: 220000, seats: 500 },
      { name: 'LLB', duration: 5, fees: 200000, seats: 200 },
      { name: 'MBA', duration: 2, fees: 450000, seats: 400 },
      { name: 'B.Sc Data Science', duration: 3, fees: 250000, seats: 200 },
    ],
  },
  {
    name: 'Christ University',
    slug: 'christ-university',
    location: 'Bengaluru, Karnataka',
    city: 'Bengaluru',
    state: 'Karnataka',
    type: 'Deemed',
    category: 'Arts',
    rating: 4.0,
    reviewCount: 980,
    annualFees: 200000,
    establishedYear: 1969,
    totalStudents: 22000,
    description: 'Christ University, Bengaluru is a renowned deemed university known for its excellence in humanities, social sciences, management, and sciences. The institution emphasizes holistic education, value formation, and global exposure through diverse programs and international partnerships with universities worldwide.',
    website: 'https://christuniversity.in',
    avgPackage: 550000,
    highestPackage: 2200000,
    placementRate: 75,
    courses: [
      { name: 'B.A. Economics', duration: 3, fees: 180000, seats: 120 },
      { name: 'B.Com', duration: 3, fees: 160000, seats: 200 },
      { name: 'BBA', duration: 3, fees: 200000, seats: 180 },
      { name: 'MBA', duration: 2, fees: 350000, seats: 120 },
      { name: 'M.Sc Psychology', duration: 2, fees: 220000, seats: 60 },
    ],
  },
  {
    name: 'Symbiosis International University',
    slug: 'symbiosis-pune',
    location: 'Pune, Maharashtra',
    city: 'Pune',
    state: 'Maharashtra',
    type: 'Deemed',
    category: 'Management',
    rating: 4.2,
    reviewCount: 750,
    annualFees: 400000,
    establishedYear: 2002,
    totalStudents: 30000,
    description: 'Symbiosis International University, Pune, is a premier deemed university with a strong focus on management, law, and applied sciences. SIBM Pune, its flagship management school, consistently ranks among India\'s top MBA programs. The university is known for its cosmopolitan campus culture and strong corporate connections.',
    website: 'https://www.siu.edu.in',
    avgPackage: 1200000,
    highestPackage: 5000000,
    placementRate: 90,
    courses: [
      { name: 'MBA', duration: 2, fees: 800000, seats: 240 },
      { name: 'BBA', duration: 3, fees: 300000, seats: 300 },
      { name: 'B.Tech Computer Science', duration: 4, fees: 400000, seats: 120 },
      { name: 'LLB', duration: 5, fees: 350000, seats: 120 },
    ],
  },
  {
    name: 'NMIMS Mumbai',
    slug: 'nmims-mumbai',
    location: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    type: 'Deemed',
    category: 'Management',
    rating: 4.3,
    reviewCount: 620,
    annualFees: 600000,
    establishedYear: 1981,
    totalStudents: 12000,
    description: 'SVKM\'s NMIMS (Narsee Monjee Institute of Management Studies) is one of Mumbai\'s most prestigious business schools. The flagship MBA program is consistently ranked among India\'s top 10 management programs. With campuses in Mumbai, Shirpur, and other cities, NMIMS blends academic rigor with real-world exposure.',
    website: 'https://www.nmims.edu',
    avgPackage: 1500000,
    highestPackage: 6000000,
    placementRate: 93,
    courses: [
      { name: 'MBA Core', duration: 2, fees: 1200000, seats: 360 },
      { name: 'BBA', duration: 3, fees: 450000, seats: 300 },
      { name: 'B.Sc Finance', duration: 3, fees: 400000, seats: 120 },
      { name: 'Pharm.D', duration: 6, fees: 550000, seats: 60 },
    ],
  },
  {
    name: 'XLRI Jamshedpur',
    slug: 'xlri-jamshedpur',
    location: 'Jamshedpur, Jharkhand',
    city: 'Jamshedpur',
    state: 'Jharkhand',
    type: 'Private',
    category: 'Management',
    rating: 4.6,
    reviewCount: 430,
    annualFees: 1100000,
    establishedYear: 1949,
    totalStudents: 1200,
    description: 'XLRI - Xavier School of Management, Jamshedpur, is one of India\'s oldest and most prestigious business schools. Founded by Jesuit priests in 1949, XLRI is renowned for its flagship HRM and Business Management programs. The institute emphasizes ethics, leadership, and social responsibility alongside academic excellence.',
    website: 'https://www.xlri.ac.in',
    avgPackage: 2500000,
    highestPackage: 10000000,
    placementRate: 98,
    courses: [
      { name: 'PGDM Business Management', duration: 2, fees: 1100000, seats: 180 },
      { name: 'PGDM Human Resource Management', duration: 2, fees: 1100000, seats: 120 },
      { name: 'FPM (PhD)', duration: 4, fees: 200000, seats: 30 },
    ],
  },
  {
    name: 'IIM Ahmedabad',
    slug: 'iim-ahmedabad',
    location: 'Ahmedabad, Gujarat',
    city: 'Ahmedabad',
    state: 'Gujarat',
    type: 'Public',
    category: 'Management',
    rating: 4.9,
    reviewCount: 520,
    annualFees: 1200000,
    establishedYear: 1961,
    totalStudents: 1000,
    description: 'IIM Ahmedabad is India\'s premier management institution and consistently ranked #1 in India for MBA programs. Established in 1961, IIMA has produced some of India\'s most successful business leaders. The institute is known for its case-method teaching, rigorous curriculum, and exceptional placement record.',
    website: 'https://www.iima.ac.in',
    avgPackage: 3500000,
    highestPackage: 15000000,
    placementRate: 100,
    courses: [
      { name: 'PGP (MBA equivalent)', duration: 2, fees: 2400000, seats: 440 },
      { name: 'Executive MBA', duration: 1, fees: 2800000, seats: 60 },
      { name: 'PhD', duration: 4, fees: 100000, seats: 20 },
    ],
  },
  {
    name: 'All India Institute of Medical Sciences Delhi',
    slug: 'aiims-delhi',
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    type: 'Public',
    category: 'Medical',
    rating: 4.9,
    reviewCount: 780,
    annualFees: 7000,
    establishedYear: 1956,
    totalStudents: 2500,
    description: 'AIIMS Delhi is India\'s most prestigious medical institution, synonymous with excellence in medical education, research, and patient care. Established in 1956, it has been at the forefront of healthcare in India. AIIMS graduates are sought after globally, and the hospital serves millions of patients every year.',
    website: 'https://www.aiims.edu',
    avgPackage: 1200000,
    highestPackage: 5000000,
    placementRate: 100,
    courses: [
      { name: 'MBBS', duration: 5, fees: 7000, seats: 107 },
      { name: 'MD Medicine', duration: 3, fees: 20000, seats: 40 },
      { name: 'MS Surgery', duration: 3, fees: 20000, seats: 30 },
      { name: 'B.Sc Nursing', duration: 4, fees: 5000, seats: 60 },
    ],
  },
  {
    name: 'Jawaharlal Nehru University',
    slug: 'jnu-delhi',
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    type: 'Public',
    category: 'Arts',
    rating: 4.4,
    reviewCount: 560,
    annualFees: 50000,
    establishedYear: 1969,
    totalStudents: 8000,
    description: 'Jawaharlal Nehru University (JNU) is one of India\'s most prestigious central universities, renowned for excellence in social sciences, humanities, international studies, and pure sciences. JNU has consistently produced leaders in academia, policy-making, and public discourse. The campus is known for its vibrant intellectual and political culture.',
    website: 'https://www.jnu.ac.in',
    avgPackage: 600000,
    highestPackage: 2000000,
    placementRate: 72,
    courses: [
      { name: 'M.A. International Relations', duration: 2, fees: 45000, seats: 40 },
      { name: 'M.A. History', duration: 2, fees: 45000, seats: 30 },
      { name: 'M.Sc. Environmental Science', duration: 2, fees: 50000, seats: 25 },
      { name: 'PhD Social Sciences', duration: 4, fees: 30000, seats: 100 },
    ],
  },
  {
    name: 'University of Delhi',
    slug: 'university-of-delhi',
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    type: 'Public',
    category: 'Arts',
    rating: 4.2,
    reviewCount: 1200,
    annualFees: 30000,
    establishedYear: 1922,
    totalStudents: 300000,
    description: 'The University of Delhi, one of India\'s largest and most prestigious universities, encompasses 91 colleges across Delhi. Known for its rigorous undergraduate programs in arts, commerce, and sciences, DU colleges like St. Stephen\'s, Lady Shri Ram, and Miranda House are among the most sought-after institutions in India.',
    website: 'http://www.du.ac.in',
    avgPackage: 500000,
    highestPackage: 2500000,
    placementRate: 70,
    courses: [
      { name: 'B.A. (Hons.) English', duration: 3, fees: 28000, seats: 60 },
      { name: 'B.Com (Hons.)', duration: 3, fees: 30000, seats: 100 },
      { name: 'B.Sc (Hons.) Mathematics', duration: 3, fees: 32000, seats: 50 },
      { name: 'LLB', duration: 3, fees: 35000, seats: 80 },
      { name: 'MBA', duration: 2, fees: 80000, seats: 40 },
    ],
  },
  {
    name: 'Tata Institute of Social Sciences',
    slug: 'tiss-mumbai',
    location: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    type: 'Public',
    category: 'Arts',
    rating: 4.4,
    reviewCount: 380,
    annualFees: 120000,
    establishedYear: 1936,
    totalStudents: 5000,
    description: 'TISS Mumbai is India\'s premier institution for social sciences and social work. Established in 1936, it offers pioneering programs in social work, human resources, education, health, and public policy. TISS is known for its critical approach to social issues, diverse student body, and strong placement in NGOs, government, and corporate sector.',
    website: 'https://www.tiss.edu',
    avgPackage: 800000,
    highestPackage: 3000000,
    placementRate: 88,
    courses: [
      { name: 'MA Social Work', duration: 2, fees: 100000, seats: 80 },
      { name: 'MA Human Resource Management', duration: 2, fees: 120000, seats: 60 },
      { name: 'MA Education', duration: 2, fees: 100000, seats: 40 },
      { name: 'M.Sc Health Administration', duration: 2, fees: 120000, seats: 30 },
    ],
  },
  {
    name: 'IIT Kharagpur',
    slug: 'iit-kharagpur',
    location: 'Kharagpur, West Bengal',
    city: 'Kharagpur',
    state: 'West Bengal',
    type: 'Public',
    category: 'Engineering',
    rating: 4.6,
    reviewCount: 890,
    annualFees: 200000,
    establishedYear: 1951,
    totalStudents: 11000,
    description: 'IIT Kharagpur, the first and oldest IIT, established in 1951, is a landmark in Indian engineering education. Located in Kharagpur, West Bengal, it has one of India\'s largest campuses. IIT KGP is known for its diverse programs, pioneering research, and highly accomplished alumni across the globe.',
    website: 'https://www.iitkgp.ac.in',
    avgPackage: 1800000,
    highestPackage: 9000000,
    placementRate: 93,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 200000, seats: 110 },
      { name: 'B.Tech Ocean Engineering', duration: 4, fees: 200000, seats: 40 },
      { name: 'B.Tech Architecture', duration: 5, fees: 200000, seats: 30 },
      { name: 'MBA', duration: 2, fees: 350000, seats: 120 },
    ],
  },
  {
    name: 'Indian Institute of Science',
    slug: 'iisc-bangalore',
    location: 'Bengaluru, Karnataka',
    city: 'Bengaluru',
    state: 'Karnataka',
    type: 'Public',
    category: 'Science',
    rating: 4.9,
    reviewCount: 450,
    annualFees: 80000,
    establishedYear: 1909,
    totalStudents: 4000,
    description: 'The Indian Institute of Science (IISc) Bengaluru is India\'s foremost research university, founded in 1909 with support from Jamsetji Tata. A leading global research institution, IISc consistently ranks as India\'s best research university. It offers programs across science, engineering, and management with a strong focus on fundamental research.',
    website: 'https://www.iisc.ac.in',
    avgPackage: 1500000,
    highestPackage: 8000000,
    placementRate: 90,
    courses: [
      { name: 'B.Sc Research', duration: 4, fees: 80000, seats: 200 },
      { name: 'M.Tech', duration: 2, fees: 90000, seats: 300 },
      { name: 'M.Sc', duration: 2, fees: 80000, seats: 150 },
      { name: 'PhD', duration: 4, fees: 60000, seats: 500 },
    ],
  },
  {
    name: 'JIPMER Puducherry',
    slug: 'jipmer-puducherry',
    location: 'Puducherry, Puducherry',
    city: 'Puducherry',
    state: 'Puducherry',
    type: 'Public',
    category: 'Medical',
    rating: 4.6,
    reviewCount: 320,
    annualFees: 10000,
    establishedYear: 1823,
    totalStudents: 1800,
    description: 'JIPMER (Jawaharlal Institute of Postgraduate Medical Education and Research) is one of India\'s premier medical institutions. Established in 1823, it is among the oldest medical schools in Asia. Located in Puducherry, JIPMER is known for its excellent medical education, research facilities, and charitable hospital services.',
    website: 'https://www.jipmer.edu.in',
    avgPackage: 1100000,
    highestPackage: 4000000,
    placementRate: 100,
    courses: [
      { name: 'MBBS', duration: 5, fees: 10000, seats: 150 },
      { name: 'MD', duration: 3, fees: 30000, seats: 60 },
      { name: 'MS', duration: 3, fees: 30000, seats: 40 },
      { name: 'B.Sc Nursing', duration: 4, fees: 8000, seats: 50 },
    ],
  },
  {
    name: 'Banaras Hindu University',
    slug: 'bhu-varanasi',
    location: 'Varanasi, Uttar Pradesh',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    type: 'Public',
    category: 'Science',
    rating: 4.0,
    reviewCount: 720,
    annualFees: 60000,
    establishedYear: 1916,
    totalStudents: 30000,
    description: 'Banaras Hindu University (BHU), founded by Pandit Madan Mohan Malviya in 1916, is one of Asia\'s largest residential universities. Located in the holy city of Varanasi, BHU offers over 300 programs across sciences, arts, engineering, medicine, and management. The sprawling 1,300-acre campus is a world unto itself.',
    website: 'https://www.bhu.ac.in',
    avgPackage: 500000,
    highestPackage: 2000000,
    placementRate: 68,
    courses: [
      { name: 'B.Sc Mathematics', duration: 3, fees: 55000, seats: 80 },
      { name: 'MBBS', duration: 5, fees: 25000, seats: 100 },
      { name: 'B.Tech Computer Science', duration: 4, fees: 65000, seats: 60 },
      { name: 'MA Sanskrit', duration: 2, fees: 45000, seats: 40 },
      { name: 'MBA', duration: 2, fees: 90000, seats: 60 },
    ],
  },
  {
    name: 'Calcutta University',
    slug: 'calcutta-university',
    location: 'Kolkata, West Bengal',
    city: 'Kolkata',
    state: 'West Bengal',
    type: 'Public',
    category: 'Arts',
    rating: 3.9,
    reviewCount: 580,
    annualFees: 25000,
    establishedYear: 1857,
    totalStudents: 400000,
    description: 'The University of Calcutta, established in 1857, is one of India\'s oldest and most esteemed universities. A hub of intellectual tradition and cultural heritage, Calcutta University has produced Nobel laureates and national leaders. It offers extensive programs in arts, sciences, commerce, law, and medicine.',
    website: 'https://www.caluniv.ac.in',
    avgPackage: 400000,
    highestPackage: 1800000,
    placementRate: 62,
    courses: [
      { name: 'B.A. English (Hons.)', duration: 3, fees: 22000, seats: 100 },
      { name: 'M.Sc Physics', duration: 2, fees: 28000, seats: 50 },
      { name: 'LLB', duration: 3, fees: 30000, seats: 80 },
      { name: 'MBA', duration: 2, fees: 60000, seats: 60 },
    ],
  },
  {
    name: 'Osmania University',
    slug: 'osmania-university',
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    type: 'Public',
    category: 'Arts',
    rating: 3.8,
    reviewCount: 480,
    annualFees: 35000,
    establishedYear: 1918,
    totalStudents: 300000,
    description: 'Osmania University, one of India\'s oldest central universities, is a landmark institution in Hyderabad. Established in 1918 by the Nizam of Hyderabad, it has a majestic campus and rich academic tradition. The university offers programs in arts, sciences, commerce, and law with affiliated colleges across Telangana.',
    website: 'https://www.osmania.ac.in',
    avgPackage: 450000,
    highestPackage: 1500000,
    placementRate: 65,
    courses: [
      { name: 'BA Political Science', duration: 3, fees: 30000, seats: 80 },
      { name: 'B.Com', duration: 3, fees: 32000, seats: 120 },
      { name: 'M.Sc Computer Science', duration: 2, fees: 38000, seats: 40 },
      { name: 'LLB', duration: 3, fees: 35000, seats: 60 },
    ],
  },
  {
    name: 'Anna University',
    slug: 'anna-university',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    type: 'Public',
    category: 'Engineering',
    rating: 4.0,
    reviewCount: 920,
    annualFees: 75000,
    establishedYear: 1978,
    totalStudents: 25000,
    description: 'Anna University is Tamil Nadu\'s premier technical university, headquartered in Chennai. Named after former Chief Minister C.N. Annadurai, it affiliates over 500 engineering colleges across Tamil Nadu. The main campus in Guindy offers quality engineering education with strong industry ties and research initiatives.',
    website: 'https://www.annauniv.edu',
    avgPackage: 700000,
    highestPackage: 3000000,
    placementRate: 80,
    courses: [
      { name: 'B.E. Computer Science', duration: 4, fees: 75000, seats: 120 },
      { name: 'B.E. Electronics & Communication', duration: 4, fees: 75000, seats: 90 },
      { name: 'B. Architecture', duration: 5, fees: 80000, seats: 40 },
      { name: 'M.E. Computer Science', duration: 2, fees: 65000, seats: 30 },
    ],
  },
  {
    name: 'Jadavpur University',
    slug: 'jadavpur-university',
    location: 'Kolkata, West Bengal',
    city: 'Kolkata',
    state: 'West Bengal',
    type: 'Public',
    category: 'Engineering',
    rating: 4.3,
    reviewCount: 550,
    annualFees: 20000,
    establishedYear: 1955,
    totalStudents: 15000,
    description: 'Jadavpur University (JU) is one of West Bengal\'s most prestigious technical universities, known for its affordable, high-quality engineering and arts education. JU consistently ranks among India\'s top 10 engineering institutions and has a vibrant research culture with numerous collaborations with international universities.',
    website: 'http://www.jaduniv.edu.in',
    avgPackage: 900000,
    highestPackage: 4000000,
    placementRate: 85,
    courses: [
      { name: 'B.E. Computer Science', duration: 4, fees: 20000, seats: 90 },
      { name: 'B.E. Electrical Engineering', duration: 4, fees: 20000, seats: 60 },
      { name: 'B.A. Comparative Literature', duration: 3, fees: 15000, seats: 40 },
      { name: 'M.E. Computer Science', duration: 2, fees: 18000, seats: 30 },
    ],
  },
  {
    name: 'Hyderabad Central University',
    slug: 'hyderabad-central-university',
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    type: 'Public',
    category: 'Science',
    rating: 4.1,
    reviewCount: 390,
    annualFees: 55000,
    establishedYear: 1974,
    totalStudents: 6000,
    description: 'The University of Hyderabad (UoH), also known as Hyderabad Central University, is a premier research institution in India. Known for its excellent research programs in sciences, social sciences, and humanities, UoH has produced numerous national scholars, scientists, and civil servants. It is recognized for its progressive academic environment.',
    website: 'https://uohyd.ac.in',
    avgPackage: 600000,
    highestPackage: 2500000,
    placementRate: 74,
    courses: [
      { name: 'M.Sc Physics', duration: 2, fees: 50000, seats: 30 },
      { name: 'M.Sc Chemistry', duration: 2, fees: 50000, seats: 30 },
      { name: 'M.A. Telugu', duration: 2, fees: 45000, seats: 20 },
      { name: 'PhD Sciences', duration: 4, fees: 40000, seats: 100 },
    ],
  },
  {
    name: 'Savitribai Phule Pune University',
    slug: 'pune-university',
    location: 'Pune, Maharashtra',
    city: 'Pune',
    state: 'Maharashtra',
    type: 'Public',
    category: 'Science',
    rating: 4.0,
    reviewCount: 680,
    annualFees: 40000,
    establishedYear: 1949,
    totalStudents: 700000,
    description: 'Savitribai Phule Pune University (SPPU), formerly University of Pune, is one of Maharashtra\'s largest and most prominent universities. With over 800 affiliated colleges, SPPU offers a wide range of programs. The main campus in Ganeshkhind is known for its lush greenery and excellent facilities for science and technology research.',
    website: 'http://www.unipune.ac.in',
    avgPackage: 550000,
    highestPackage: 2000000,
    placementRate: 70,
    courses: [
      { name: 'M.Sc Computer Science', duration: 2, fees: 40000, seats: 60 },
      { name: 'M.Sc Biotechnology', duration: 2, fees: 42000, seats: 30 },
      { name: 'MBA', duration: 2, fees: 80000, seats: 60 },
      { name: 'LLB', duration: 3, fees: 35000, seats: 80 },
    ],
  },
  {
    name: 'PSG College of Technology',
    slug: 'psg-tech-coimbatore',
    location: 'Coimbatore, Tamil Nadu',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    type: 'Private',
    category: 'Engineering',
    rating: 4.0,
    reviewCount: 520,
    annualFees: 140000,
    establishedYear: 1951,
    totalStudents: 8000,
    description: 'PSG College of Technology, Coimbatore, is a leading private engineering college in Tamil Nadu. Established in 1951, it is known for its academic excellence, industry partnerships, and strong placement record. PSG Tech has a unique "earn while you learn" policy and robust industry collaboration through its PSG & Sons\' Charities trust.',
    website: 'https://www.psgtech.edu',
    avgPackage: 800000,
    highestPackage: 3500000,
    placementRate: 87,
    courses: [
      { name: 'B.E. Computer Science', duration: 4, fees: 140000, seats: 180 },
      { name: 'B.E. Mechanical Engineering', duration: 4, fees: 130000, seats: 120 },
      { name: 'B.E. Electronics & Communication', duration: 4, fees: 140000, seats: 120 },
      { name: 'MBA', duration: 2, fees: 180000, seats: 60 },
    ],
  },
  {
    name: 'Aligarh Muslim University',
    slug: 'amu-aligarh',
    location: 'Aligarh, Uttar Pradesh',
    city: 'Aligarh',
    state: 'Uttar Pradesh',
    type: 'Public',
    category: 'Arts',
    rating: 3.9,
    reviewCount: 640,
    annualFees: 45000,
    establishedYear: 1875,
    totalStudents: 30000,
    description: 'Aligarh Muslim University (AMU), one of India\'s oldest and most prestigious central universities, was founded in 1875 by Sir Syed Ahmed Khan. Known for its emphasis on education for Muslim minorities and excellence in sciences, humanities, and engineering, AMU has a rich cultural heritage and distinguished alumni.',
    website: 'https://www.amu.ac.in',
    avgPackage: 480000,
    highestPackage: 1800000,
    placementRate: 67,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 50000, seats: 60 },
      { name: 'MBBS', duration: 5, fees: 30000, seats: 100 },
      { name: 'LLB', duration: 5, fees: 40000, seats: 80 },
      { name: 'MBA', duration: 2, fees: 60000, seats: 60 },
    ],
  },
  {
    name: 'IIT Roorkee',
    slug: 'iit-roorkee',
    location: 'Roorkee, Uttarakhand',
    city: 'Roorkee',
    state: 'Uttarakhand',
    type: 'Public',
    category: 'Engineering',
    rating: 4.5,
    reviewCount: 720,
    annualFees: 215000,
    establishedYear: 1847,
    totalStudents: 7500,
    description: 'IIT Roorkee, formerly the University of Roorkee, is the oldest technical institute in Asia, established in 1847. It attained IIT status in 2001. Located in Roorkee, Uttarakhand, IIT Roorkee is known for its excellent engineering programs, rich history, and strong alumni network across the globe.',
    website: 'https://www.iitr.ac.in',
    avgPackage: 1700000,
    highestPackage: 8500000,
    placementRate: 92,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 215000, seats: 100 },
      { name: 'B.Tech Civil Engineering', duration: 4, fees: 215000, seats: 80 },
      { name: 'B.Arch', duration: 5, fees: 215000, seats: 35 },
      { name: 'MBA', duration: 2, fees: 350000, seats: 60 },
    ],
  },
  {
    name: 'Lovely Professional University',
    slug: 'lpu-phagwara',
    location: 'Phagwara, Punjab',
    city: 'Phagwara',
    state: 'Punjab',
    type: 'Private',
    category: 'Engineering',
    rating: 3.6,
    reviewCount: 2800,
    annualFees: 180000,
    establishedYear: 2006,
    totalStudents: 300000,
    description: 'Lovely Professional University (LPU) is one of India\'s largest private universities, spread across a vast 600-acre campus in Punjab. Known for its diverse student body, numerous international students, wide range of programs, and state-of-the-art facilities, LPU offers a unique blend of academics and co-curricular activities.',
    website: 'https://www.lpu.in',
    avgPackage: 550000,
    highestPackage: 3000000,
    placementRate: 76,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 180000, seats: 2000 },
      { name: 'B.Tech Data Science', duration: 4, fees: 200000, seats: 500 },
      { name: 'MBA', duration: 2, fees: 250000, seats: 800 },
      { name: 'B.Design', duration: 4, fees: 220000, seats: 200 },
      { name: 'MBBS', duration: 5, fees: 800000, seats: 100 },
    ],
  },
  {
    name: 'Chandigarh University',
    slug: 'chandigarh-university',
    location: 'Gharuan, Punjab',
    city: 'Gharuan',
    state: 'Punjab',
    type: 'Private',
    category: 'Engineering',
    rating: 3.8,
    reviewCount: 1900,
    annualFees: 160000,
    establishedYear: 2012,
    totalStudents: 80000,
    description: 'Chandigarh University (CU) is a leading private university in Punjab, known for its modern infrastructure, strong industry partnerships, and active placement cell. CU holds numerous records in Guinness World Records and is popular among students for its entrepreneurship culture and diverse academic offerings.',
    website: 'https://www.cuchd.in',
    avgPackage: 600000,
    highestPackage: 4000000,
    placementRate: 80,
    courses: [
      { name: 'B.E. Computer Science', duration: 4, fees: 160000, seats: 1500 },
      { name: 'B.E. AI & ML', duration: 4, fees: 180000, seats: 400 },
      { name: 'MBA', duration: 2, fees: 220000, seats: 600 },
      { name: 'LLB', duration: 5, fees: 150000, seats: 200 },
    ],
  },
  {
    name: 'Vellore Institute of Technology Chennai',
    slug: 'vit-chennai',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    type: 'Deemed',
    category: 'Engineering',
    rating: 3.9,
    reviewCount: 800,
    annualFees: 330000,
    establishedYear: 2010,
    totalStudents: 20000,
    description: 'VIT Chennai campus, established as a satellite campus of VIT Vellore, offers the same quality engineering education in the heart of Tamil Nadu\'s capital city. The campus is equipped with modern laboratories, research centres, and provides excellent placement opportunities with leading MNCs and product companies.',
    website: 'https://chennai.vit.ac.in',
    avgPackage: 780000,
    highestPackage: 4000000,
    placementRate: 83,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 330000, seats: 500 },
      { name: 'B.Tech Cyber Security', duration: 4, fees: 350000, seats: 200 },
      { name: 'M.Tech Software Engineering', duration: 2, fees: 260000, seats: 60 },
    ],
  },
  {
    name: 'RV College of Engineering',
    slug: 'rvce-bangalore',
    location: 'Bengaluru, Karnataka',
    city: 'Bengaluru',
    state: 'Karnataka',
    type: 'Private',
    category: 'Engineering',
    rating: 4.1,
    reviewCount: 610,
    annualFees: 190000,
    establishedYear: 1963,
    totalStudents: 6000,
    description: 'RV College of Engineering (RVCE), Bengaluru is one of Karnataka\'s most prestigious private engineering colleges, established by the Rashtreeya Sikshana Samithi Trust. Located in the heart of India\'s Silicon Valley, RVCE benefits from excellent industry exposure, strong alumni network, and outstanding placement record.',
    website: 'https://www.rvce.edu.in',
    avgPackage: 950000,
    highestPackage: 5000000,
    placementRate: 88,
    courses: [
      { name: 'B.E. Computer Science', duration: 4, fees: 190000, seats: 180 },
      { name: 'B.E. Electronics & Communication', duration: 4, fees: 180000, seats: 120 },
      { name: 'B.E. Mechanical Engineering', duration: 4, fees: 175000, seats: 120 },
      { name: 'M.Tech Computer Science', duration: 2, fees: 150000, seats: 30 },
    ],
  },
  {
    name: 'IIIT Hyderabad',
    slug: 'iiit-hyderabad',
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    type: 'Deemed',
    category: 'Engineering',
    rating: 4.4,
    reviewCount: 420,
    annualFees: 280000,
    establishedYear: 1998,
    totalStudents: 3000,
    description: 'IIIT Hyderabad is an autonomous research university focused on computing and related fields. Known for its research-first approach, IIIT-H integrates research into undergraduate education from the first year. It has strong international collaborations and is a hub for AI, ML, and computer vision research in India.',
    website: 'https://www.iiit.ac.in',
    avgPackage: 2200000,
    highestPackage: 9000000,
    placementRate: 94,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 280000, seats: 150 },
      { name: 'B.Tech Electronics & Communication', duration: 4, fees: 280000, seats: 60 },
      { name: 'M.Tech Computer Science', duration: 2, fees: 250000, seats: 100 },
      { name: 'MS by Research', duration: 2, fees: 200000, seats: 200 },
    ],
  },
  {
    name: 'Coimbatore Institute of Technology',
    slug: 'cit-coimbatore',
    location: 'Coimbatore, Tamil Nadu',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    type: 'Private',
    category: 'Engineering',
    rating: 3.9,
    reviewCount: 430,
    annualFees: 120000,
    establishedYear: 1956,
    totalStudents: 5000,
    description: 'Coimbatore Institute of Technology (CIT) is an autonomous engineering college in Coimbatore, Tamil Nadu. Established in 1956, it is one of the oldest and most respected engineering colleges in the region. CIT is known for its strong alumni network, industry connections, and quality teaching in core engineering disciplines.',
    website: 'https://www.cit.edu.in',
    avgPackage: 650000,
    highestPackage: 2800000,
    placementRate: 82,
    courses: [
      { name: 'B.E. Computer Science', duration: 4, fees: 120000, seats: 120 },
      { name: 'B.E. Mechanical Engineering', duration: 4, fees: 110000, seats: 90 },
      { name: 'B.E. Civil Engineering', duration: 4, fees: 110000, seats: 60 },
    ],
  },
  {
    name: 'NIT Surathkal',
    slug: 'nit-surathkal',
    location: 'Surathkal, Karnataka',
    city: 'Surathkal',
    state: 'Karnataka',
    type: 'Public',
    category: 'Engineering',
    rating: 4.2,
    reviewCount: 510,
    annualFees: 145000,
    establishedYear: 1960,
    totalStudents: 5500,
    description: 'NIT Surathkal (National Institute of Technology Karnataka) is one of the top NITs in India, situated on the scenic Arabian Sea coastline near Mangaluru. The institute offers high-quality engineering education with strong research programs and excellent placements. Its coastal campus is known for its unique and vibrant student culture.',
    website: 'https://www.nitk.ac.in',
    avgPackage: 1000000,
    highestPackage: 4000000,
    placementRate: 86,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 145000, seats: 90 },
      { name: 'B.Tech Information Technology', duration: 4, fees: 145000, seats: 60 },
      { name: 'B.Tech Electrical Engineering', duration: 4, fees: 145000, seats: 60 },
      { name: 'M.Tech Computer Science', duration: 2, fees: 120000, seats: 25 },
    ],
  },
  {
    name: 'Shiv Nadar University',
    slug: 'shiv-nadar-university',
    location: 'Greater Noida, Uttar Pradesh',
    city: 'Greater Noida',
    state: 'Uttar Pradesh',
    type: 'Private',
    category: 'Engineering',
    rating: 4.0,
    reviewCount: 380,
    annualFees: 420000,
    establishedYear: 2011,
    totalStudents: 7000,
    description: 'Shiv Nadar University (SNU) is a multidisciplinary research university established by HCL Technologies founder Shiv Nadar. Located in Greater Noida, SNU offers liberal arts-based engineering and science education. Known for its research focus, international faculty, and vibrant campus culture in a 286-acre green campus.',
    website: 'https://snu.edu.in',
    avgPackage: 1100000,
    highestPackage: 5000000,
    placementRate: 88,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 420000, seats: 200 },
      { name: 'B.Tech Electrical Engineering', duration: 4, fees: 400000, seats: 80 },
      { name: 'B.Sc Mathematics', duration: 3, fees: 350000, seats: 60 },
      { name: 'MBA', duration: 2, fees: 600000, seats: 60 },
    ],
  },
  {
    name: 'Ashoka University',
    slug: 'ashoka-university',
    location: 'Sonipat, Haryana',
    city: 'Sonipat',
    state: 'Haryana',
    type: 'Private',
    category: 'Arts',
    rating: 4.3,
    reviewCount: 280,
    annualFees: 750000,
    establishedYear: 2014,
    totalStudents: 3000,
    description: 'Ashoka University is India\'s premier liberal arts and sciences institution, founded in 2014. Modeled after leading US liberal arts colleges, it offers a unique interdisciplinary Young India Fellowship, economics, computer science, and humanities programs. Ashoka attracts top faculty from global universities and boasts a distinguished set of founders from Indian industry.',
    website: 'https://www.ashoka.edu.in',
    avgPackage: 900000,
    highestPackage: 4000000,
    placementRate: 84,
    courses: [
      { name: 'B.Sc Economics', duration: 3, fees: 750000, seats: 80 },
      { name: 'B.Sc Computer Science', duration: 3, fees: 750000, seats: 60 },
      { name: 'BA English & Media', duration: 3, fees: 700000, seats: 50 },
      { name: 'MA Economics', duration: 2, fees: 600000, seats: 40 },
    ],
  },
  {
    name: 'Sanjay Gandhi Post Graduate Institute of Medical Sciences',
    slug: 'sgpgi-lucknow',
    location: 'Lucknow, Uttar Pradesh',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    type: 'Public',
    category: 'Medical',
    rating: 4.3,
    reviewCount: 290,
    annualFees: 15000,
    establishedYear: 1983,
    totalStudents: 2000,
    description: 'SGPGI Lucknow is one of India\'s leading postgraduate medical research institutes, known for super-specialty care and research. Established in 1983, it focuses on postgraduate medical education and is a Centre of Excellence for organ transplantation in North India. The institute serves patients from across Uttar Pradesh and neighboring states.',
    website: 'https://www.sgpgi.ac.in',
    avgPackage: 1400000,
    highestPackage: 5000000,
    placementRate: 100,
    courses: [
      { name: 'DM (Super Specialty)', duration: 3, fees: 15000, seats: 50 },
      { name: 'MCh Surgery', duration: 3, fees: 15000, seats: 30 },
      { name: 'MD', duration: 3, fees: 12000, seats: 60 },
      { name: 'PhD Medicine', duration: 4, fees: 10000, seats: 40 },
    ],
  },
  {
    name: 'Presidency College Chennai',
    slug: 'presidency-college-chennai',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    type: 'Public',
    category: 'Arts',
    rating: 3.9,
    reviewCount: 340,
    annualFees: 15000,
    establishedYear: 1840,
    totalStudents: 5000,
    description: 'Presidency College, Chennai, established in 1840, is one of Asia\'s oldest colleges. A government autonomous institution, it offers programs in arts, sciences, and commerce. Known for its historic legacy, distinguished alumni, and strong academic tradition, Presidency College remains one of Tamil Nadu\'s most respected institutions.',
    website: 'http://www.presidencychennai.com',
    avgPackage: 400000,
    highestPackage: 1500000,
    placementRate: 65,
    courses: [
      { name: 'B.Sc Mathematics', duration: 3, fees: 15000, seats: 60 },
      { name: 'B.Sc Physics', duration: 3, fees: 15000, seats: 40 },
      { name: 'B.A. History', duration: 3, fees: 12000, seats: 40 },
      { name: 'M.Sc Computer Science', duration: 2, fees: 18000, seats: 30 },
    ],
  },
  {
    name: 'OP Jindal Global University',
    slug: 'op-jindal-global-university',
    location: 'Sonipat, Haryana',
    city: 'Sonipat',
    state: 'Haryana',
    type: 'Private',
    category: 'Arts',
    rating: 4.2,
    reviewCount: 320,
    annualFees: 450000,
    establishedYear: 2009,
    totalStudents: 10000,
    description: 'OP Jindal Global University (JGU) is India\'s leading research-driven global university, known for its innovative programs in law, business, international affairs, and liberal arts. JGU has top national rankings for law and business programs and extensive global faculty. The university is a member of prestigious global university networks.',
    website: 'https://www.jgu.edu.in',
    avgPackage: 900000,
    highestPackage: 4000000,
    placementRate: 85,
    courses: [
      { name: 'BA LLB (Hons.)', duration: 5, fees: 450000, seats: 300 },
      { name: 'BBA', duration: 3, fees: 400000, seats: 200 },
      { name: 'MA Diplomacy', duration: 2, fees: 380000, seats: 60 },
      { name: 'MBA', duration: 2, fees: 600000, seats: 180 },
    ],
  },
  {
    name: 'Madras Medical College',
    slug: 'madras-medical-college',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    type: 'Public',
    category: 'Medical',
    rating: 4.2,
    reviewCount: 450,
    annualFees: 12000,
    establishedYear: 1835,
    totalStudents: 2500,
    description: 'Madras Medical College (MMC), established in 1835, is one of the oldest and most prestigious medical colleges in Asia. Located in Chennai, it is affiliated with The Tamil Nadu Dr. M.G.R. Medical University. MMC\'s teaching hospital, Rajiv Gandhi Government General Hospital, is one of the largest hospitals in India.',
    website: 'http://www.mmc.tn.gov.in',
    avgPackage: 1100000,
    highestPackage: 4500000,
    placementRate: 99,
    courses: [
      { name: 'MBBS', duration: 5, fees: 12000, seats: 250 },
      { name: 'MD', duration: 3, fees: 25000, seats: 100 },
      { name: 'MS', duration: 3, fees: 25000, seats: 80 },
      { name: 'B.Sc Nursing', duration: 4, fees: 8000, seats: 60 },
    ],
  },
  {
    name: 'NIT Warangal',
    slug: 'nit-warangal',
    location: 'Warangal, Telangana',
    city: 'Warangal',
    state: 'Telangana',
    type: 'Public',
    category: 'Engineering',
    rating: 4.2,
    reviewCount: 490,
    annualFees: 140000,
    establishedYear: 1959,
    totalStudents: 6000,
    description: 'NIT Warangal, the first Regional Engineering College in India, established in 1959, is a premier technical institution in Telangana. Known for its excellent research facilities, industry connections, and vibrant student life, NIT Warangal consistently features among India\'s top engineering colleges with strong placement statistics.',
    website: 'https://nitw.ac.in',
    avgPackage: 1000000,
    highestPackage: 4500000,
    placementRate: 87,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 140000, seats: 90 },
      { name: 'B.Tech Electronics', duration: 4, fees: 140000, seats: 90 },
      { name: 'B.Tech Metallurgical Engineering', duration: 4, fees: 140000, seats: 40 },
      { name: 'MBA', duration: 2, fees: 200000, seats: 60 },
    ],
  },
  {
    name: 'King George\'s Medical University',
    slug: 'kgmu-lucknow',
    location: 'Lucknow, Uttar Pradesh',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    type: 'Public',
    category: 'Medical',
    rating: 4.1,
    reviewCount: 380,
    annualFees: 20000,
    establishedYear: 1905,
    totalStudents: 3000,
    description: 'King George\'s Medical University (KGMU), Lucknow, established in 1905, is one of India\'s oldest medical universities. Named after King George V, KGMU has produced some of India\'s finest doctors and surgeons. It is the nodal medical university for Uttar Pradesh and runs several medical colleges and hospitals.',
    website: 'https://kgmu.org',
    avgPackage: 1200000,
    highestPackage: 5000000,
    placementRate: 98,
    courses: [
      { name: 'MBBS', duration: 5, fees: 20000, seats: 250 },
      { name: 'MD', duration: 3, fees: 40000, seats: 100 },
      { name: 'BDS', duration: 5, fees: 15000, seats: 60 },
    ],
  },
  {
    name: 'Thapar Institute of Engineering and Technology',
    slug: 'thapar-institute',
    location: 'Patiala, Punjab',
    city: 'Patiala',
    state: 'Punjab',
    type: 'Deemed',
    category: 'Engineering',
    rating: 4.0,
    reviewCount: 540,
    annualFees: 350000,
    establishedYear: 1956,
    totalStudents: 12000,
    description: 'Thapar Institute of Engineering and Technology, Patiala, is a premier private technical university established in 1956. Known for its industry-oriented curriculum, research programs, and strong placement record, Thapar consistently attracts top companies for recruitment. The institute has strategic partnerships with leading global universities.',
    website: 'https://www.thapar.edu',
    avgPackage: 900000,
    highestPackage: 4200000,
    placementRate: 86,
    courses: [
      { name: 'B.E. Computer Science', duration: 4, fees: 350000, seats: 300 },
      { name: 'B.E. Electronics & Communication', duration: 4, fees: 330000, seats: 180 },
      { name: 'B.E. Mechanical Engineering', duration: 4, fees: 330000, seats: 180 },
      { name: 'MBA', duration: 2, fees: 400000, seats: 60 },
    ],
  },
  {
    name: 'Maharaja Sayajirao University of Baroda',
    slug: 'msu-baroda',
    location: 'Vadodara, Gujarat',
    city: 'Vadodara',
    state: 'Gujarat',
    type: 'Public',
    category: 'Arts',
    rating: 3.9,
    reviewCount: 420,
    annualFees: 30000,
    establishedYear: 1949,
    totalStudents: 40000,
    description: 'The Maharaja Sayajirao University of Baroda (MSU) is one of Gujarat\'s premier universities, known for its excellence in fine arts, performing arts, and sciences. Established in 1949, MSU\'s Faculty of Fine Arts is one of the most renowned in Asia. The university offers diverse programs across 11 faculties.',
    website: 'https://www.msubaroda.ac.in',
    avgPackage: 450000,
    highestPackage: 1800000,
    placementRate: 68,
    courses: [
      { name: 'B.F.A. (Fine Arts)', duration: 4, fees: 25000, seats: 100 },
      { name: 'M.Sc Chemistry', duration: 2, fees: 30000, seats: 40 },
      { name: 'BBA', duration: 3, fees: 32000, seats: 80 },
      { name: 'LLB', duration: 3, fees: 28000, seats: 60 },
    ],
  },
  {
    name: 'IISER Pune',
    slug: 'iiser-pune',
    location: 'Pune, Maharashtra',
    city: 'Pune',
    state: 'Maharashtra',
    type: 'Public',
    category: 'Science',
    rating: 4.5,
    reviewCount: 290,
    annualFees: 70000,
    establishedYear: 2006,
    totalStudents: 2500,
    description: 'IISER Pune (Indian Institute of Science Education and Research) is a premier autonomous research institute established in 2006. Focused on fundamental sciences, IISER Pune offers an integrated BS-MS program and PhD programs in physics, chemistry, mathematics, biology, and earth sciences. It is a place for students passionate about basic research.',
    website: 'https://www.iiserpune.ac.in',
    avgPackage: 900000,
    highestPackage: 4000000,
    placementRate: 82,
    courses: [
      { name: 'BS-MS Dual Degree', duration: 5, fees: 70000, seats: 200 },
      { name: 'PhD Physics', duration: 4, fees: 50000, seats: 60 },
      { name: 'PhD Chemistry', duration: 4, fees: 50000, seats: 50 },
      { name: 'PhD Mathematics', duration: 4, fees: 50000, seats: 40 },
    ],
  },
  {
    name: 'Pune Institute of Computer Technology',
    slug: 'pict-pune',
    location: 'Pune, Maharashtra',
    city: 'Pune',
    state: 'Maharashtra',
    type: 'Private',
    category: 'Engineering',
    rating: 4.0,
    reviewCount: 390,
    annualFees: 180000,
    establishedYear: 1983,
    totalStudents: 3500,
    description: 'Pune Institute of Computer Technology (PICT) is one of Pune\'s most prestigious private engineering colleges, renowned for its Computer and IT programs. Located in the city centre, PICT benefits from Pune\'s thriving IT ecosystem, providing students with excellent internship and placement opportunities with leading tech companies.',
    website: 'https://pict.edu',
    avgPackage: 800000,
    highestPackage: 4000000,
    placementRate: 87,
    courses: [
      { name: 'B.E. Computer Engineering', duration: 4, fees: 180000, seats: 300 },
      { name: 'B.E. Information Technology', duration: 4, fees: 180000, seats: 180 },
      { name: 'M.E. Computer Engineering', duration: 2, fees: 150000, seats: 30 },
    ],
  },
  {
    name: 'College of Engineering Pune',
    slug: 'coep-pune',
    location: 'Pune, Maharashtra',
    city: 'Pune',
    state: 'Maharashtra',
    type: 'Public',
    category: 'Engineering',
    rating: 4.1,
    reviewCount: 510,
    annualFees: 100000,
    establishedYear: 1854,
    totalStudents: 5000,
    description: 'College of Engineering Pune (COEP), established in 1854, is one of the oldest engineering colleges in India and Asia. A government autonomous institution under Savitribai Phule Pune University, COEP is known for its strong academic tradition, excellent faculty, and outstanding alumni network in engineering and technology.',
    website: 'https://www.coep.org.in',
    avgPackage: 850000,
    highestPackage: 3800000,
    placementRate: 87,
    courses: [
      { name: 'B.E. Computer Engineering', duration: 4, fees: 100000, seats: 120 },
      { name: 'B.E. Electronics', duration: 4, fees: 100000, seats: 90 },
      { name: 'B.E. Mechanical Engineering', duration: 4, fees: 95000, seats: 90 },
      { name: 'M.E. Computer Engineering', duration: 2, fees: 90000, seats: 30 },
    ],
  },
  {
    name: 'Sri Venkateswara University',
    slug: 'svuniversity-tirupati',
    location: 'Tirupati, Andhra Pradesh',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    type: 'Public',
    category: 'Science',
    rating: 3.8,
    reviewCount: 350,
    annualFees: 32000,
    establishedYear: 1954,
    totalStudents: 20000,
    description: 'Sri Venkateswara University (SVU), Tirupati, established in 1954, is one of Andhra Pradesh\'s premier universities. Named after the revered deity at Tirupati, the university offers comprehensive programs in sciences, arts, and engineering. SVU is known for its research programs and has produced numerous academics and civil servants.',
    website: 'https://www.svuniversity.edu.in',
    avgPackage: 420000,
    highestPackage: 1600000,
    placementRate: 66,
    courses: [
      { name: 'M.Sc Mathematics', duration: 2, fees: 30000, seats: 40 },
      { name: 'M.Sc Computer Science', duration: 2, fees: 35000, seats: 40 },
      { name: 'M.A. Telugu', duration: 2, fees: 25000, seats: 30 },
      { name: 'PhD Science', duration: 4, fees: 28000, seats: 80 },
    ],
  },
  {
    name: 'Birla Institute of Technology Mesra',
    slug: 'bit-mesra',
    location: 'Mesra, Jharkhand',
    city: 'Mesra',
    state: 'Jharkhand',
    type: 'Deemed',
    category: 'Engineering',
    rating: 3.9,
    reviewCount: 460,
    annualFees: 250000,
    establishedYear: 1955,
    totalStudents: 9000,
    description: 'Birla Institute of Technology (BIT) Mesra, established in 1955 near Ranchi, is a deemed university known for quality technical education in Jharkhand. Located on a 785-acre campus, BIT Mesra offers programs in engineering, pharmacy, management, and sciences with a focus on practical and research-oriented education.',
    website: 'https://www.bitmesra.ac.in',
    avgPackage: 700000,
    highestPackage: 3500000,
    placementRate: 79,
    courses: [
      { name: 'B.E. Computer Science', duration: 4, fees: 250000, seats: 120 },
      { name: 'B.E. Electronics & Communication', duration: 4, fees: 240000, seats: 90 },
      { name: 'MBA', duration: 2, fees: 300000, seats: 60 },
      { name: 'B.Pharm', duration: 4, fees: 200000, seats: 60 },
    ],
  },
  {
    name: 'Maulana Azad National Institute of Technology',
    slug: 'manit-bhopal',
    location: 'Bhopal, Madhya Pradesh',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    type: 'Public',
    category: 'Engineering',
    rating: 4.0,
    reviewCount: 420,
    annualFees: 135000,
    establishedYear: 1960,
    totalStudents: 7000,
    description: 'Maulana Azad National Institute of Technology (MANIT) Bhopal is a premier NIT in Madhya Pradesh, established in 1960. MANIT offers excellent engineering programs, research opportunities, and strong placement support. The campus in Bhopal is well-equipped with modern labs, a sports complex, and student activity centers.',
    website: 'https://www.manit.ac.in',
    avgPackage: 850000,
    highestPackage: 3800000,
    placementRate: 83,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 135000, seats: 75 },
      { name: 'B.Tech Electronics', duration: 4, fees: 135000, seats: 75 },
      { name: 'B.Tech Civil Engineering', duration: 4, fees: 135000, seats: 60 },
      { name: 'MBA', duration: 2, fees: 180000, seats: 60 },
    ],
  },
  {
    name: 'Delhi Technological University',
    slug: 'dtu-delhi',
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    type: 'Public',
    category: 'Engineering',
    rating: 4.1,
    reviewCount: 680,
    annualFees: 170000,
    establishedYear: 1941,
    totalStudents: 11000,
    description: 'Delhi Technological University (DTU), formerly Delhi College of Engineering, is one of Delhi\'s oldest and most prestigious engineering institutions. Established in 1941, DTU offers a comprehensive range of technical programs. Located in Rohini, Delhi, it benefits from its proximity to India\'s capital city and its vibrant tech ecosystem.',
    website: 'http://www.dtu.ac.in',
    avgPackage: 1200000,
    highestPackage: 5500000,
    placementRate: 89,
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, fees: 170000, seats: 180 },
      { name: 'B.Tech Software Engineering', duration: 4, fees: 170000, seats: 60 },
      { name: 'B.Tech Electronics & Communication', duration: 4, fees: 165000, seats: 120 },
      { name: 'MBA', duration: 2, fees: 250000, seats: 60 },
    ],
  },
  {
    name: 'Jawaharlal Institute of Technology',
    slug: 'jit-nagpur',
    location: 'Nagpur, Maharashtra',
    city: 'Nagpur',
    state: 'Maharashtra',
    type: 'Private',
    category: 'Engineering',
    rating: 3.5,
    reviewCount: 280,
    annualFees: 130000,
    establishedYear: 1998,
    totalStudents: 4000,
    description: 'Jawaharlal Institute of Technology (JIT) Nagpur is a private engineering institution in Central India\'s major city. The college offers programs in computer science, mechanical, civil, and electrical engineering. JIT is known for its affordable fees, good faculty-student ratio, and improving placement record with regional companies.',
    website: 'https://jit.ac.in',
    avgPackage: 450000,
    highestPackage: 1800000,
    placementRate: 72,
    courses: [
      { name: 'B.E. Computer Science', duration: 4, fees: 130000, seats: 120 },
      { name: 'B.E. Mechanical Engineering', duration: 4, fees: 120000, seats: 60 },
      { name: 'B.E. Civil Engineering', duration: 4, fees: 120000, seats: 60 },
    ],
  },
  {
    name: 'Sri Ramachandra Institute of Higher Education',
    slug: 'sri-ramachandra-university',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    type: 'Deemed',
    category: 'Medical',
    rating: 4.1,
    reviewCount: 360,
    annualFees: 1500000,
    establishedYear: 1985,
    totalStudents: 5000,
    description: 'Sri Ramachandra Institute of Higher Education (SRIHER), Chennai, is a prestigious deemed university combining a medical college, hospital, and allied health sciences. Known for its advanced medical training, SRIHER offers MBBS, MD, MS, and numerous allied health programs. The attached teaching hospital handles over a million patient visits annually.',
    website: 'https://www.sriramachandra.edu.in',
    avgPackage: 1000000,
    highestPackage: 4000000,
    placementRate: 96,
    courses: [
      { name: 'MBBS', duration: 5, fees: 1500000, seats: 150 },
      { name: 'BDS', duration: 5, fees: 900000, seats: 80 },
      { name: 'B.Sc Nursing', duration: 4, fees: 400000, seats: 100 },
      { name: 'B.Pharm', duration: 4, fees: 350000, seats: 60 },
    ],
  },
  {
    name: 'Guru Nanak Dev University',
    slug: 'gndu-amritsar',
    location: 'Amritsar, Punjab',
    city: 'Amritsar',
    state: 'Punjab',
    type: 'Public',
    category: 'Arts',
    rating: 3.8,
    reviewCount: 390,
    annualFees: 28000,
    establishedYear: 1969,
    totalStudents: 15000,
    description: 'Guru Nanak Dev University (GNDU), Amritsar, established in 1969 to mark the 500th birth anniversary of Guru Nanak Dev Ji, is a premier university in Punjab. Known for its programs in arts, humanities, sports sciences, and engineering, GNDU has one of the best sports facilities in the country and regularly produces national-level athletes.',
    website: 'https://www.gndu.ac.in',
    avgPackage: 420000,
    highestPackage: 1600000,
    placementRate: 65,
    courses: [
      { name: 'B.A. (Hons.) Punjabi', duration: 3, fees: 25000, seats: 60 },
      { name: 'M.Sc Computer Science', duration: 2, fees: 30000, seats: 40 },
      { name: 'BBA', duration: 3, fees: 28000, seats: 80 },
      { name: 'MBA', duration: 2, fees: 55000, seats: 60 },
    ],
  },
  {
    name: 'Institute of Chemical Technology Mumbai',
    slug: 'ict-mumbai',
    location: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    type: 'Public',
    category: 'Engineering',
    rating: 4.2,
    reviewCount: 310,
    annualFees: 90000,
    establishedYear: 1933,
    totalStudents: 2500,
    description: 'The Institute of Chemical Technology (ICT) Mumbai, formerly UDCT, is a premier autonomous institution for chemical technology and engineering. India\'s only institute ranked among the top 50 universities globally for Chemistry, ICT has produced leaders in the chemical, pharmaceutical, and petrochemical industries worldwide.',
    website: 'https://www.ictmumbai.edu.in',
    avgPackage: 1000000,
    highestPackage: 5000000,
    placementRate: 91,
    courses: [
      { name: 'B.Chem.Engg.', duration: 4, fees: 90000, seats: 60 },
      { name: 'B.Pharm', duration: 4, fees: 85000, seats: 60 },
      { name: 'M.Chem.Engg.', duration: 2, fees: 80000, seats: 30 },
      { name: 'PhD', duration: 4, fees: 60000, seats: 60 },
    ],
  },
]

async function main() {
  console.log('🌱 Starting seed...')

  // Clear existing data
  await prisma.savedCollege.deleteMany()
  await prisma.review.deleteMany()
  await prisma.course.deleteMany()
  await prisma.college.deleteMany()

  console.log('🗑️  Cleared existing college data')

  for (const college of colleges) {
    const { courses, ...collegeData } = college
    const created = await prisma.college.create({
      data: {
        ...collegeData,
        courses: {
          create: courses,
        },
      },
    })
    console.log(`✅ Created: ${created.name}`)
  }

  console.log(`\n🎉 Seed complete! Created ${colleges.length} colleges.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
